<?php global $con; ?>

<p><strong>Record Information</strong></p>
<div class="uiForm">
    <form action="" id="valid2" class="mainForm mainAjaxForm">
    	<input type="hidden" id="plugstruid" value="<?=$_POST['plugstrcuid'];?>" />
    	<input type="hidden" id="fid" value="<?=$this->recordsetInfo['fieldsetId'];?>" />
    	<input type="hidden" id="record_id" value="<?=$this->recordsetInfo['id'];?>" />
    	<label class="dialog">Type</label>
        <select name="record_type" id="record_type" style="floaT:left;"  onchange="customlaunch(this.value);">
            <option value="text" <?=($this->recordsetInfo['type']=="text"?"selected":"");?>>Text</option>
            <option value="textarea" <?=($this->recordsetInfo['type']=="textarea"?"selected":"");?>>Textarea</option>
            <option value="number" <?=($this->recordsetInfo['type']=="number"?"selected":"");?>>Number</option>
            <option value="email" <?=($this->recordsetInfo['type']=="email"?"selected":"");?>>Email</option>
            <option value="radio" <?=($this->recordsetInfo['type']=="radio"?"selected":"");?>>Radio</option>
            <option value="checkboxes" <?=($this->recordsetInfo['type']=="checkboxes"?"selected":"");?>>Checkboxes</option>
            <option value="select" <?=($this->recordsetInfo['type']=="select"?"selected":"");?>>Select</option>
            <option value="multiselect" <?=($this->recordsetInfo['type']=="multiselect"?"selected":"");?>>Multiple Select</option>
            <option value="html" <?=($this->recordsetInfo['type']=="html"?"selected":"");?>>HTML</option>
            <option value="yesno" <?=($this->recordsetInfo['type']=="yesno"?"selected":"");?>>Yes/No</option>
            <option value="date" <?=($this->recordsetInfo['type']=="date"?"selected":"");?>>Date</option>
            <option value="time" <?=($this->recordsetInfo['type']=="time"?"selected":"");?>>Time</option>
            <option value="color" <?=($this->recordsetInfo['type']=="color"?"selected":"");?>>Color</option>
            <option value="file" <?=($this->recordsetInfo['type']=="file"?"selected":"");?>>Single File</option>
            <option value="photo" <?=($this->recordsetInfo['type']=="photo"?"selected":"");?>>Photo</option>
            <option value="multiphoto" <?=($this->recordsetInfo['type']=="multiphoto"?"selected":"");?>>Multiple Photos</option>
            <option value="custom_url" <?=($this->recordsetInfo['type']=="custom_url"?"selected":"");?>>Custom URL</option>
			<option value="foreignkey" <?=($this->recordsetInfo['type']=="foreignkey"?"selected":"");?>>Foreign Key</option>
			<option value="include" <?=($this->recordsetInfo['type']=="custom"?"selected":"");?>>Inlcude</option>
            <option value="ukpostcode" <?=($this->recordsetInfo['type']=="ukpostcode"?"selected":"");?>>UK PostCode</option>
		</select>
        <div id="fkey" <? if($this->recordsetInfo['type']!="foreignkey") { ?>style="display:none;"<? }?>>
            <label class="dialog">Foreign Key</label>
            <select style="floaT:left;" id="record_fkey" name="record_fkey">
            	<? $fk_q = 'SELECT * FROM cms_plugin_structure WHERE id <> "'.$_POST['plugstrcuid'].'"';
				   $fk_r = mysqli_query($con,$fk_q) or die(mysqli_error($con));
				   while($fk = mysqli_fetch_array($fk_r,MYSQLI_ASSOC)){?>
                   		<option value="<?=$fk['id'];?>" <?=($this->recordsetInfo['fkey']==$fk['id']?"selected":"");?>><?=$fk['name'];?></option>
                <? } ?>
            </select>
    	</div>
    	<label class="dialog">Name</label>
        <input type="text" value="<?=$this->recordsetInfo['name']?>" onkeypress="return handleEnter(this, event)" name="record_name" id="record_name"/>
    	<label class="dialog">Database Name</label>
        <input type="text" value="<?=$this->recordsetInfo['db_name']?>" <?=($this->recordsetInfo['type']=="custom_url"?"disabled":"");?> onkeypress="return handleEnter(this, event)" name="record_dbname" id="record_dbname"/>
    	<div id="photoResize"  <? if($this->recordsetInfo['type']!="photo") { ?>style="display:none;"<? }?>>
	    	<label class="dialog">Photo Resize Options</label>
	        <input type="text" value="<?=$this->recordsetInfo['photoresize']?>" name="record_photoresize" onkeypress="return handleEnter(this, event)" id="record_photoresize"/>
    	</div>
    	<div id="customUrl"  <? if($this->recordsetInfo['type']!="custom_url") { ?>style="display:none;"<? }?>>
	    	<label class="dialog">Custom Url</label>
	        <input type="text" value="<?=$this->recordsetInfo['custom_url']?>" name="record_customurl" onkeypress="return handleEnter(this, event)" id="record_customurl"/>
    	</div>
    	<label class="dialog">Helper</label>
        <input type="text" value="<?=$this->recordsetInfo['helper']?>" name="record_helper" onkeypress="return handleEnter(this, event)" id="record_helper"/>
    	<label class="dialog">Options</label>
        <textarea id="record_options" name="record_options" rows="5"><?=$this->recordsetInfo['options']?></textarea>
        <script>
		function customlaunch(val) {
			if(val=="foreignkey") {
				$("#fkey").show();
				$("#customUrl").hide();
				$("#photoResize").hide();
				$("#record_dbname").val("").removeAttr("disabled");
			} else if(val=="photo") {
				$("#photoResize").show();
				$("#customUrl").hide();
				$("#fkey").hide();
				$("#record_dbname").val("").removeAttr("disabled");
			} else if(val=="custom_url") {
				$("#customUrl").show();
				$("#photoResize").hide();
				$("#fkey").hide();
				$("#record_dbname").val("custom_url").attr("disabled",true);
			} else {
				$("#photoResize").hide();
				$("#customUrl").hide();
				$("#fkey").hide();
				$("#record_dbname").val("").removeAttr("disabled");
			}
		}
		function save(){
			$.ajax({
				type: 'POST',
				dataType: "json",
				url: "<?=_EQROOT_;?>cms_plugins/save_record_structure",
				data: {
					'fid': $("#fid").val(),
					'rid': $("#record_id").val(),
					'plugstruid': $("#plugstruid").val(),
					'record_type': $("#record_type").val(),
					'record_name': $("#record_name").val(),
					'record_dbname': $("#record_dbname").val(),
					'record_helper': $("#record_helper").val(),
					'record_options': $("#record_options").val(),
					'record_fkey': $("#record_fkey").val(),
					'record_photoresize': $("#record_photoresize").val(),
					'record_customurl': $("#record_customurl").val()
				},
                beforeSend: function(){
                    $.getJSON('<?=_EQROOT_;?>login/check_status', function(check) {
                        if(check.status == 'loggedout'){
                            window.location = '<?=_EQROOT_;?>';
                            return false;
                        }
                    });
                },success: function (data) {
					if (data.response == "sqlerror") {
						alert('Sorry, but that database name is a reserved SQL keyword, please use another one.');
						$('#comStrucDiv');
					}else if (data.response == "matchingfields"){
						alert('Sorry, but there is already a database-name named "' + $("#record_dbname").val() + '" in this fieldset.');
						$('#comStrucDiv');
					}else if (data.response == "emptyfields"){
						alert('Please do not leave the "Name" and/or "Database Name" fields empty.');
						$('#comStrucDiv');
					}else if (data.response == "success"){
						$('#comStrucDiv').load("<?=_EQROOT_;?>cms_plugins/show_plugin_structure?pluginid=<?=$this->recordsetInfo['pluginid']?>");
						$('#dialog-message').dialog( "close" );
						$('#dialog-message').html('');
					}
				}
			});
		}
		function deletethis(){
			$.ajax({
				type: 'POST',
				url: "<?=_EQROOT_;?>cms_plugins/delete_record_structure",
				data: {
					'rid': $("#record_id").val()
				},
				success: function(msg){
					//$( "#comStrucDiv" ).html(msg);
					$('#comStrucDiv').load("<?=_EQROOT_;?>cms_plugins/show_plugin_structure?pluginid=<?=$this->recordsetInfo['pluginid']?>");
					$('#dialog-message').dialog( "close" );
					$('#dialog-message').html('');
				}
			});
		}
		$(document).ready(function(){
			$("#record_dbname").keyup(function() {
			  str = $(this).val();
			  $(this).val(str.toLowerCase().replace(/[^a-z0-9\s]/gi, '').replace(/[_\s]/g, '_'));
			});
		});
		</script>
    </form>
</div>
