<p><strong>Fieldset Information</strong></p>
<div class="uiForm">
     <form id="valid2" class="mainForm mainAjaxForm">
    	<input type="hidden" id="fieldsetid" value="<?=$this->fieldsetInfo['id'];?>" />
        <label class="dialog">Name</label>
        <input type="text" value="<?=$this->fieldsetInfo['name'];?>" onkeypress="return handleEnter(this, event)" name="fieldsetname" id="fieldsetname"/>
    </form>
	<script>
    	function save() {
			$.ajax({
				type: 'POST',
				dataType: 'json',
				url: '<?=_EQROOT_;?>cms_plugins/save_fieldset_structure',
				data: { 
					'fid': $("#fieldsetid").val(),
					'name': $("#fieldsetname").val()
				},
				beforeSend: function() {
					$.getJSON('<?=_EQROOT_;?>login/check_status', function(check) {
                        if(check.status == 'loggedout'){
                            window.location = '<?=_EQROOT_;?>';
                            return false;
                        } else {
                            $('#comStrucDiv').css({'opacity':'0.6'});
                        }
                    });
				},
				success: function(data) {
					if (data.response == "success") {
						$('#dialog-message').dialog('close');
						$('#dialog-message').html('');
						$('#comStrucDiv').css({'opacity':'1'}).load("<?=_EQROOT_;?>cms_plugins/show_plugin_structure?pluginid=<?=$this->fieldsetInfo['pluginid'];?>");
					} else if (data.response == "error") {
						alert('Please enter a Fieldset Name.');
						$('#comStrucDiv').css({'opacity':'1'});
					}
				}
			});
		}
		function deletethis() {
			var r = confirm("Are you sure you want to delete this fieldset?\nAll the records below it will be deleted as well.");
			if (r == true) {
				   
				$.ajax({
					type: 'POST',
					url: "<?=_EQROOT_;?>cms_plugins/delete_fieldset_structure",
					data: { 
						'fid': $("#fieldsetid").val()
					},
					success: function(msg) {
						$('#dialog-message').dialog('close');
						$('#dialog-message').html('');
						$('#comStrucDiv').css({'opacity':'1'}).load("<?=_EQROOT_;?>cms_plugins/show_plugin_structure?pluginid=<?=$this->fieldsetInfo['pluginid'];?>");
					}
				});
			}
		}
	</script>
</div>