<div class="table first">
    <div class="head"><h5><i class="fa fa-flag"></i>Campaigns</h5></div>
    <div class="divbody">
        <table cellpadding="0" cellspacing="0" width="100%" class="tableStatic">
            <thead>
                <tr>
                    <td>Name</td>
                    <td>Subject</td>
                    <td>Date</td>
                    <td>Status</td>
                </tr>
            </thead>
            <tbody>
                 <? foreach($this->campaign as $campaign){?>
                    <tr>
                        <td align="center"><a href="<?=_EQROOT_.'mail/view/'.$campaign['id'];?>"><?=$campaign['name'];?></a></td>
                        <td align="center"><small><?=date("F j, Y, g:i a",strtotime($campaign['date']));?></small></td>
                        <td align="center"><small><?=date("F j, Y, g:i a",strtotime($campaign['date']));?></small></td>
                        <td align="center"><strong class="<?=($campaign['status']==1?"green":"red");?>">[ <?=($campaign['status']==1?"Pending":"Sent");?> ]</strong></td>
                    </tr>
                 <? }?>
            </tbody>
        </table>
    </div>
</div>