<form action="<?=_EQROOT_?>mail/view/<?=$this->c['id'];?>" method="post" id="valid" class="mainForm" enctype="multipart/form-data">
<fieldset>
<input type="hidden" name="campaign" value="1" />
<input type="hidden" name="id" value="<?=$this->c['id'];?>" />
<input type="hidden" id="cats" value='<?=$this->cat;?>' />
<input type="hidden" id="contacts" value="<?=$this->c['cats'];?>" />
	<div class="widget first">
	<div class="head"><h5>Campaign Details</h5><div class="loader"></div></div> 

    <div class="rowElem noborder">
        <label>Campaign Name:</label>
        <div class="formRight">
            <input type="text" class="validate[]" name="name" id="name" value="<?=$this->c['name'];?>"/>
        </div>
        <div class="fix"></div>
    </div>

    <div class="rowElem">
        <label>From Name:</label>
        <div class="formRight">
            <input type="text" class="validate[]" name="fromname" id="fromname" value="<?=$this->c['fromname'];?>"/>
        </div>
        <div class="fix"></div>
    </div>

    <div class="rowElem">
        <label>From Email:</label>
        <div class="formRight">
            <input type="text" class="validate[custom[email]]" name="fromemail" id="fromemail" value="<?=$this->c['fromemail'];?>"/>
        </div>
        <div class="fix"></div>
    </div>

    <div class="rowElem">
        <label>To:</label>
        <div class="formRight">
            <select name="contact[]" id="contact" multiple="" class="chzn-select validate[]"></select>
        </div>
        <div class="fix"></div>
    </div>

    <div class="rowElem">
        <label>Subject:</label>
        <div class="formRight">
            <input type="text" class="validate[]" name="subject" id="subject" value="<?=$this->c['subject'];?>"/>
        </div>
        <div class="fix"></div>
    </div>
    <div class="rowElem">
        <label>Mail Body:</label>
        <div class="formRight">
            <textarea class="tinymce" name="body"><?=$this->c['body'];?></textarea>
        </div>
        <div class="fix"></div>
    </div>
    

    <div class="rowElem">
        <label>Attachment:</label>
        <div class="formRight">
        	<? if($this->c['attachment']) { ?>
        	<a href="<?=_UPLOADS_.'mail/'.$this->c['attachment'];?>" target="_blank" class="attachmentfile"><?=$this->c['attachment'];?></a><br/>
        	<? } ?>
            <input type="file" name="file" id="file">
        <div class="fix"></div>
    </div>
    
    <div class="fix"></div>
                
    <div class="rowElem formaction noborder">
        <div class="formRight">
      		<button type="button" id="sendCampaign" class="blueBtn floatright">Send Campaign</button>
      		<input type="submit" value="Save Campaign" class="greyishBtn floatright">
      		<button type="button" class="redBtn floatright">Delete Campaign</button>
        </div>
   		<div class="fix"></div>
    </div>

	</div>
</fieldset>
</form>
<div id="result"></div>