    </div>
    <!-- end content -->
        <div class="fix"></div>
    </div>
    <!-- end content -->
    
    <!-- Footer -->
    <div id="footer">
        <div class="wrapper">
            <span>&copy; Copyright <?=date("Y");?>. All rights reserved.</span>
        </div>
    </div>	
    
    </body>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/defines.js"></script>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/spinner/jquery.mousewheel.js"></script>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/spinner/ui.spinner.js"></script>

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script> 
    <script type="text/javascript" src="<?=EQ_PUB;?>js/jsapi.js"></script>

    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/tables/jquery.dataTables.js"></script>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/tables/colResizable.min.js"></script>

    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/forms/jquery.form.min.js"></script>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/forms/forms.js"></script>

    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/forms/autotab.js"></script>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/forms/jquery.validationEngine-en.js"></script>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/forms/jquery.validationEngine.js"></script>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/forms/jquery.dualListBox.js"></script>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/forms/jquery.inputlimiter.min.js"></script>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/forms/jquery.tagsinput.min.js"></script>

        <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/other/elfinder.min.js"></script>

    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/ui/jquery.jgrowl.js"></script>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/ui/jquery.tipsy.js"></script>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/ui/jquery.alerts.js"></script>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/ui/jquery.colorpicker.js"></script>

    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/wizards/jquery.validate.js"></script>

    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/ui/jquery.collapsible.min.js"></script>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/ui/jquery.ToTop.js"></script>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/ui/jquery.listnav.js"></script>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/ui/jquery.timeentry.min.js"></script>
    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/tinymce/tinymce.min.js"></script>

    <script type="text/javascript" src="<?=EQ_PUB;?>js/plugins/session/jquery.session.js"></script>

    <script type="text/javascript" src="<?=EQ_PUB;?>js/custom.js"></script>

    <?php $this->jsToHead();?>
</html>
