<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<title><?=$this->title;?> - Admin</title>

<link href="<?=EQ_PUB;?>css/main.css" rel="stylesheet" type="text/css" />
<link href="<?=EQ_PUB;?>css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script> 
<?php $this->cssToHead();?>

</head>

<body data-siteroot="<?=_EQROOT_;?>">

