
<!-- Login form area -->
<div class="loginWrapper">

	<div class="loginLogo" style="top:-129px; left:30%;">
		<a href="<?=_EQROOT_;?>">equinox</a>
	</div>
	
    <div class="nNote nFailure hideit displaynone"></div>
    <div class="loginPanel">
        <div class="head"><h5><i class="fa fa-sign-in fa-1x"></i>Login</h5></div>
        <form action="<?=_EQROOT_;?>login/process" method="post" id="valid" class="mainForm">
            <fieldset style="display:-webkit-inline-box">
                <div class="loginRow noborder">
                    <label for="req1">Email:</label>
                    <div class="loginInput"><input type="text" name="username" class="validate[required,custom[email]]" id="req1" /></div>
                    <div class="fix"></div>
                </div>
                
                <div class="loginRow">
                    <label for="req2">Password:</label>
                    <div class="loginInput"><input type="password" name="password" class="validate[required]" id="req2" /></div>
                    <div class="fix"></div>
                </div>
                
                <div class="loginRow">                	
                    <div class="rememberMe"></div>
                    <input type="submit" value="Log me in" class="greyishBtn submitForm floatright" />
                    <div class="fix"></div>
                </div>
            </fieldset>
        </form>
    </div>
    
</div>


<div id="divToUpdate"></div>