<form action="<?=_EQROOT_?>contacts/addcat" method="post" id="valid" class="mainForm">
<fieldset>
	<div class="widget first">
	<div class="head"><h5 class="iInfo">Category Info</h5><div class="loader"></div></div>
		<div class="rowElem noborder"><label>Name:</label><div class="formRight"><input type="text" class="validate[required]" name="name" id="name"/></div><div class="fix"></div></div>
		<div class="fix"></div>
        <div class="rowElem formaction noborder">
			<input type="submit" value="Add Category" class="greyishBtn floatright">
            <div class="fix"></div>
        </div>

	</div>
</fieldset>
</form>

<div id="divToUpdate"></div>