<br/>
<a class="addButton modal mr10" href="<?=_EQROOT_;?>contacts/addcat">Add Contact Category</a>   
 <!-- Dynamic table -->
<div class="table first">
    <div class="head"><h5 class="iFrames">Contacts Categories List</h5></div>
    <table cellpadding="0" cellspacing="0" border="0" class="display" id="example">
        <thead>
            <tr>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
        <? foreach($this->cats as $cat){ ?>
            <tr class="gradeA" align="center">
                <td><a href="<?=_EQROOT_;?>contacts/editcat/<?=$cat['id'];?>"><?=$cat['name'];?></a></td>
            </tr>
        <? }?>
        </tbody>
    </table>
</div>