<!-- Contact list -->
<br/>
<a class="addButton modal mr10" href="<?=_EQROOT_;?>contacts/add"><i class="fa fa-plus-square fa-1x"></i>Add Contact</a>   
<a class="importFile modal mr10" href="<?=_EQROOT_;?>contacts/import"><i class="fa fa-upload fa-1x"></i>Import Contact List</a>



<select style="float:right;" onchange="window.location.href=this.options[this.selectedIndex].value">
		<option value="<?=_EQROOT_.'contacts';?>">All Categories</option> 
    	<? foreach($this->contactCats as $contactCat){ ?>
    		<option value="<?=$this->eqapp->url_prefix($_SERVER['REQUEST_URI'],"cats",$contactCat['id'])?>" <? if(isset($_GET['cats'])){ if($_GET['cats']==$contactCat['id']) { echo "selected"; } } ?>><?=$contactCat['name'];?></option>             
    	<? } ?>
</select> 
    
<div class="widget first">
    <div class="head"><h5><i class="fa fa-users fa-1x"></i>Contacts list</h5>
    	<input type="text" id="searchCont" style="float:right; margin:9px 20px; padding:2px;" placeholder="search.." value="<?=Apps::iset('search');?>"/>
    </div>
    <div id="myList-nav"></div>
    <? if(count($this->contacts)==0){
        echo '</br>';
        echo '<h4 align=center>Sorry there are no contact in your list</h4>';
        echo '</br>';
    }?>

        <ul id="myList">
			<? foreach($this->contacts as $contact){ ?>
                <li><a href="<?=_EQROOT_;?>contacts/edit/<?=$contact['id'];?>"><?=$contact['fname'].' '.$contact['lname'];?></a>
                    <ul class="listData">
                        <li><a href="mailto:<?=$contact['email'];?>" title=""><?=$contact['email'];?></a></li>
                        <? if($contact['phone']){?><li><span class="red"><?=$contact['phone'];?></span></li><? } ?>
                        <? if($contact['mobile']){?><li><span class="red"><?=$contact['mobile'];?></span></li><? } ?>
                        <? if($contact['company']){?><li><span class="cnote"><?=$contact['company'];?></span></li><? } ?>
                    </ul>
                </li>
            <? } ?>
        </ul>
    <div class="fix"></div>
</div>